import type { DatatableLabels } from './types'

export const defaultLabels: DatatableLabels = {
  search: 'Search…',
  searchDisabled: 'Show a searchable column to search',
  columns: 'Columns',
  filters: 'Filters',
  filtersDescription: 'Narrow the results with extra conditions.',
  any: 'Any',
  from: 'from',
  to: 'to',
  reset: 'Reset',
  applyFilters: 'Apply filters',
  selected: (count) => `${count} selected`,
  bulkAction: 'Bulk action',
  actions: 'Actions…',
  apply: 'Apply',
  applying: 'Applying…',
  selectAll: 'Select all',
  selectRow: 'Select row',
  loading: 'Loading…',
  error: "Couldn't load the data.",
  retry: 'Retry',
  noResults: 'No results.',
  total: (count) => `${count} total`,
  page: (page, pages) => `Page ${page} of ${pages}`,
  previous: 'Previous',
  next: 'Next',
}
